### ISSUE TITLE
Issue with installing gulp-webdriver

### ISSUE THREAD

**Issue by imRichardNg** [webdriverio/gulp-webdriver#37]
I have issue installing gulp-webdriver.
After some debugging, it seems that this occurs during the installation of `dargs` dependencies.

Could the developers please take a look? Thanks.

Command: 
`npm install gulp-webdriver --save-dev`
Error:

```
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:818:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:469:12)
npm WARN addRemoteGit  christian-bromann/dargs resetting remote C:\...\AppData\Roaming\npm-cache\_git-remotes\
git-github-com-christian-bromann-dargs-git-d1658d6c because of error: { [Error: Command failed: git -c core.longpaths=true co
nfig --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
```

**Comment by FBerthelot** [comment]
I have the same problem, I guess you have like me a company proxy which block github access.

@christian-bromann can you consider to publish your dargs component in npm ?

**Comment by imRichardNg** [comment]
@FBerthelot ur right. I am behind proxy which blocks github access.

**Comment by FBerthelot** [comment]
Many thanks ;)
