### ISSUE TITLE
Test hangs on failure...

### ISSUE THREAD

**Issue by sjerman** [webdriverio/gulp-webdriver#52]
I have this task:

```
gulp.task('e2e',['start-rest','start-server','selenium'], function (done) {
     gulp.src('wdio.conf.js')
        .pipe(webdriver())
        .on('end', function(err){
            console.log(">>2>>"+err);
            done(err);
        })
        .on('error', function(err){
            console.log(">>>>"+err);
            done(err);
        });
});
```

It works fine when the tests pass, but hangs on failure:

```
0 passing (17.70s)
1 failing

1) Basic Test Should be able to login ..:
Failed: element (nsa-content) still not existing after 10000ms
running chrome
Error: element (nsa-content) still not existing after 10000ms
    at Page.value (test/e2e/spec/common/MainAssurancePage.js:27:18)
    at Object.<anonymous> (test/e2e/spec/testSpec.js:27:27)
    at elements("nsa-content") - isExisting.js:46:17
    at isExisting("nsa-content") - waitForExist.js:37:22

Wrote xunit report to [./target/test-res].
>>>>Error in plugin 'gulp-webdriver'
Message:
    wdio exited with code 1
[11:42:50] 'e2e' errored after 18 s
[11:42:50] Error in plugin 'gulp-webdriver'
Message:
    wdio exited with code 1
```

The versions of the plugins etc are:

gulp-webdriver@2.0.2
webdriverio@4.4.0

Any suggestions?

**Comment by christian-bromann** [comment]
Should be fixed with latest version
